### ISSUE TITLE
Problem with PR line duplication

### ISSUE THREAD

**Issue by marcry** [Olivr/free-domain#1014]
Every time i try to register i get an error like this.
i cant modify one line if the last line doesnt have a line break

![image](https://github.com/Olivr/free-domain/assets/8473709/30272bd6-b861-4fd3-8372-ac83dbae3f95)

**Comment by pandaninjas** [comment]
Pretty stupidly, GitHub's web editor will add a newline at the end of the file. You have to edit it locally.

**Comment by santydesignscr** [comment]
I created a website to auto register domains: test.bytewave.wip.la (is beta, but working)

**Comment by pandaninjas** [comment]
> I created a website to auto register domains: test.bytewave.wip.la (is beta, but working)
> 
> Also you can see my main website: bytewave.wip.la

Unfortunately, it seems like this service is not updating new domain names anymore

**Comment by santydesignscr** [comment]
Yes I seen, I created a domain and is not working yet, only my existing bytewave.wip.la works right now in my side

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains, in my plataform you can register a subdomain, edit NS:
https://nic.webcr.top/app
