### ISSUE TITLE
All subdomains seemingly no longer work.

### ISSUE THREAD

**Issue by l2vy7** [Olivr/free-domain#114]
All subdomains on both wip.la and cluster.ws look like they don't work anymore.  
From testing with my own new subdomain which should be set up correctly (```l2vy7.cluster.ws```) and example subdomains (```example.cluster.ws```, ```example.wip.la```), all subdomains seemingly now do not resolve.  
This may or may not be an issue with the DNS providers.

**Comment by politician** [comment]
@l2vy7 sorry I just saw this issue. 

- I just tested, everything works correctly.
- I looked at the Git and Terraform logs over the past few days and nothing weird happened.
- Both `cluster.ws` and `wip.la` zones are on CloudFlare and they [didn't report](https://www.cloudflarestatus.com/) any DNS incident in the last few days.

Maybe it was a temporary outage from your ISP or their DNS provider.
