### ISSUE TITLE
Consider adding cluster.ws to the PSL

### ISSUE THREAD

**Issue by IncognitoTGT** [Olivr/free-domain#1179]
This would make it a proper TLD and make it compatible with Cloudflare
Info: https://publicsuffix.org/
Apply: https://publicsuffix.org/submit/

**Comment by TechClusterHQ** [comment]
Why was this closed as not planned? Did the public suffix registry reject the request?

**Comment by IncognitoTGT** [comment]
Yea they rejected it

**Comment by TechClusterHQ** [comment]
Was there a specific reason or did they just not like this awesome service?

**Comment by IncognitoTGT** [comment]
something as in "being used to circumvent technical restrictions."
https://github.com/publicsuffix/list/pull/1523
