### ISSUE TITLE
Auto-Merged PR but NS Records for nhr.cluster.ws Not Updated

### ISSUE THREAD

**Issue by nazdridoy** [Olivr/free-domain#1523]
PR #1520 got auto-merged successfully, but the sub-domain nhr.cluster.ws still doesn't have the right NS records.

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains, in my plataform you can register a subdomain, edit NS:
https://nic.webcr.top/app

**Comment by politician** [comment]
> PR #1520 got auto-merged successfully, but the sub-domain nhr.cluster.ws still doesn't have the right NS records.


Sorry, new registrations don't work anymore. See #1955
