### ISSUE TITLE
Using this for myself

### ISSUE THREAD

**Issue by anondev-sudo** [Olivr/free-domain#159]
Hello, could I use this code to make my own subdomain service? Where do I set cloudflare API key?

**Comment by anondev-sudo** [comment]
Does it auto add name server records to cloudflare?

**Comment by politician** [comment]
Yes you can, just fork the repo.

The code to manage domains is in `main.tf`, it's using Terraform with the [Cloudflare provider](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs)

Register on Terraform Cloud and point it at your repo, set the required env variables for the Cloudflare provider there.

**Comment by anondev-sudo** [comment]
Is that service free? Or do you need to pay for their cloud services?

**Comment by anondev-sudo** [comment]
I thought that GitHub action manages it

**Comment by politician** [comment]
> Is that service free? Or do you need to pay for their cloud services?

Please do your own research

**Comment by politician** [comment]
> I thought that GitHub action manages it

Github Actions manages the automerge flow. But everything still works without Github actions, you'd just have to approve merge requests manually.
