### ISSUE TITLE
AutoMerge but not really did not sync with the DNS since the ns requests do not reach the subdomain

### ISSUE THREAD

**Issue by pocholo30** [Olivr/free-domain#1664]
Good, I am using FreeDNS because for the domain cluster.ws ClouDNS does not allow it, even so once the pull request was made I did not get the ns requests are redirected to the subdomain, still appears the same when doing the nslookup that when it is not registered, let a few days to see if it took some time but still does not work, try with wip.la and cloudns and worked without problems.

**Comment by py660** [comment]
same here! dns doesn't work

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains, in my plataform you can register a subdomain, edit NS:
https://nic.webcr.top/app
