### ISSUE TITLE
Where to put DNS records? For wip.la 

### ISSUE THREAD

**Issue by Priyansxu** [Olivr/free-domain#1695]

**Comment by santydesignscr** [comment]
I created a website to auto register domains: test.bytewave.wip.la (is beta, but working)

**Comment by Priyansxu** [comment]
Is the site is safe? Anyways can you dm me on Instagram?

**Comment by santydesignscr** [comment]
Yes, sure, instagram dm: santy._.cr

**Comment by santydesignscr** [comment]
The website is sure, but beta, no security tests yet, anyways the website don't handle sensitive info (only my github access key)

**Comment by santydesignscr** [comment]
Your domain was sucessfully registered, your first attemp from the website worked

**Comment by santydesignscr** [comment]
Anyways if you want dm me

**Comment by Priyansxu** [comment]
> Your domain was sucessfully registered, your first attemp from the website worked

Actually I was just testing so I put website url which is not servernames, i don't know where to get nameserver on cloudflarenfor the subdomain, I've used it's pages.dev url, can help me with nameserver?

**Comment by santydesignscr** [comment]
Yes sure, can you pm on instagram, to continue from my cellphone (current on the pc)

**Comment by Priyansxu** [comment]
> Yes sure, can you pm on instagram, to continue from my cellphone (current on the pc)

Okay, I've dmed you! Anyways thanks for the support

**Comment by santydesignscr** [comment]
I dont get your message

**Comment by santydesignscr** [comment]
Your instagram username?

**Comment by Priyansxu** [comment]
> Your instagram username?

priyansxu_gupta

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains, in my plataform you can register a subdomain, edit NS:
https://nic.webcr.top/app
