### ISSUE TITLE
Auto-Merged then "All checks have failed"

### ISSUE THREAD

**Issue by winnieyuen** [Olivr/free-domain#1758]
Already Auto-Merged: #1757 
But then it displays:
All checks have failed
1 failing check
@terraform-cloud
Terraform Cloud/olivr/free-domain — Terraform apply errored

I cannot use the domain. Please help to check. Thank you.

**Comment by winnieyuen** [comment]
![image](https://github.com/Olivr/free-domain/assets/83917861/9287b281-071f-4e72-9a06-bc1c0ad38d05)

**Comment by santydesignscr** [comment]
Hello everyone,

I've just launched a new option for free subdomains at [NIC.WEBCR.TOP](https://nic.webcr.top). It's a straightforward process compared to the .wip.la registration method.

With NIC.WEBCR.TOP:
- **Register .webcr.top Subdomains:** Get your own .webcr.top subdomain quickly.
- **Edit Nameservers:** Easily manage your subdomains by adjusting nameservers.
- **Eliminate Subdomains:** Remove any unwanted subdomains effortlessly.

Now there won't be any issues with the pull request not being auto-merged. Additionally, this platform allows you to edit the nameservers of your subdomains and remove unused subdomains.

**Comment by politician** [comment]
> Already Auto-Merged: #1757 But then it displays: All checks have failed 1 failing check @terraform-cloud Terraform Cloud/olivr/free-domain — Terraform apply errored
> 
> I cannot use the domain. Please help to check. Thank you.


Sorry, new registrations don't work anymore. See #1955
