### ISSUE TITLE
[HELP] How to verify if domain is registered

### ISSUE THREAD

**Issue by AmanSarraf** [Olivr/free-domain#1764]
I followed the steps in README and edited file respective to wip.la , now how to verify if the domain is registered, I am using cloudns

![Screenshot from 2023-12-31 15-16-37](https://github.com/Olivr/free-domain/assets/90839355/08fe1b71-e6a7-44bb-b6d5-2c2eafe0fb10)

screenshot for cloudns dashboard

![Screenshot from 2023-12-31 15-17-23](https://github.com/Olivr/free-domain/assets/90839355/713ff80e-8b08-4285-b35b-023f0fccfdd2)

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains, in my plataform you can register a subdomain, edit NS:
https://nic.webcr.top/app

**Comment by politician** [comment]
> I followed the steps in README and edited file respective to wip.la , now how to verify if the domain is registered, I am using cloudns
> 
> ![Screenshot from 2023-12-31 15-16-37](https://private-user-images.githubusercontent.com/90839355/293499409-08fe1b71-e6a7-44bb-b6d5-2c2eafe0fb10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Mzc5OTgsIm5iZiI6MTcxMTYzNzY5OCwicGF0aCI6Ii85MDgzOTM1NS8yOTM0OTk0MDktMDhmZTFiNzEtZTZhNy00NGJiLWI2ZDUtMmMyZWFmZTBmYjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0NTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNDI5MDE0MzhhYjYzNDZjNWM4NDBiYzYxOGM1ODNhOWE0MDUxYzg2MWRhODBlYmQwOTU0YmMyNzFlMGQ1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xGS9hr_CLdhNpU9sBU9iNp_Hf45slYN3dbd_XCyAFC0)
> 
> screenshot for cloudns dashboard
> 
> ![Screenshot from 2023-12-31 15-17-23](https://private-user-images.githubusercontent.com/90839355/293499414-713ff80e-8b08-4285-b35b-023f0fccfdd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Mzc5OTgsIm5iZiI6MTcxMTYzNzY5OCwicGF0aCI6Ii85MDgzOTM1NS8yOTM0OTk0MTQtNzEzZmY4MGUtOGIwOC00Mjg1LWIzNWItMDIzZjBmY2NmZGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0NTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmY4NzczNjViMWJhMDdjMmQ4MzNlZWRjMmJkN2QxMzJlOTYxMjc4NzA4MzY3N2Y4MGU2ZDEzMGRiN2E1YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wlWGvTF6BwSPPCQXTs4hl2qIZWyoishaJePeoE6PA7E)


Sorry, new registrations don't work anymore. See #1955
