### ISSUE TITLE
Dns records not registering

### ISSUE THREAD

**Issue by KrazyKleb** [Olivr/free-domain#1844]
It's been almost 24 hours

**Comment by rishavdas494** [comment]
doesnt work anymore

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains, in my plataform you can register a subdomain, edit NS:
https://nic.webcr.top/app

**Comment by politician** [comment]
> It's been almost 24 hours


Sorry, new registrations don't work anymore. See #1955
