### ISSUE TITLE
Does this service work now?

### ISSUE THREAD

**Issue by Sekler09** [Olivr/free-domain#1881]
I created two domains. One with FreeDNS and one with ClouDNS. Both are not working.

**Comment by rishavdas494** [comment]
i guess no

**Comment by santydesignscr** [comment]
Hello everyone, it seems that this subdomain is not currently working, I recommend this platform that I just launched, the subdomain is webcr.top, apparently there are almost no subdomains:
https://nic.webcr.top/app

**Comment by morningdew2008** [comment]
> Hello everyone,
> 
> I've just launched a new option for free subdomains at [NIC.WEBCR.TOP](https://nic.webcr.top). It's a straightforward process compared to the .wip.la registration method.
> 
> With NIC.WEBCR.TOP:
> 
> * **Register .webcr.top Subdomains:** Get your own .webcr.top subdomain quickly.
> * **Edit Nameservers:** Easily manage your subdomains by adjusting nameservers.
> * **Eliminate Subdomains:** Remove any unwanted subdomains effortlessly.
> 
> Now there won't be any issues with the pull request not being auto-merged. Additionally, this platform allows you to edit the nameservers of your subdomains and remove unused subdomains.

It works. Thank you very much!

**Comment by santydesignscr** [comment]
> > Hello everyone,
> > I've just launched a new option for free subdomains at [NIC.WEBCR.TOP](https://nic.webcr.top). It's a straightforward process compared to the .wip.la registration method.
> > With NIC.WEBCR.TOP:
> > 
> > * **Register .webcr.top Subdomains:** Get your own .webcr.top subdomain quickly.
> > * **Edit Nameservers:** Easily manage your subdomains by adjusting nameservers.
> > * **Eliminate Subdomains:** Remove any unwanted subdomains effortlessly.
> > 
> > Now there won't be any issues with the pull request not being auto-merged. Additionally, this platform allows you to edit the nameservers of your subdomains and remove unused subdomains.
> 
> It works. Thank you very much!

Nice to know that it works for you, thanks for your feedback

**Comment by politician** [comment]
> I created two domains. One with FreeDNS and one with ClouDNS. Both are not working.

Sorry, new registrations don't work anymore. See #1955
