### ISSUE TITLE
New subdomain option, for Free!

### ISSUE THREAD

**Issue by santydesignscr** [Olivr/free-domain#1925]
Hello everyone,

I've just launched a new option for free subdomains at [NIC.WEBCR.TOP](https://nic.webcr.top). It's a straightforward process compared to the .wip.la registration method.

With NIC.WEBCR.TOP:
- **Register .webcr.top Subdomains:** Get your own .webcr.top subdomain quickly.
- **Edit Nameservers:** Easily manage your subdomains by adjusting nameservers.
- **Eliminate Subdomains:** Remove any unwanted subdomains effortlessly.

Now there won't be any issues with the pull request not being auto-merged. Additionally, this platform allows you to edit the nameservers of your subdomains and remove unused subdomains.

**Comment by cnsn521** [comment]
Thank you, I have already applied for the addition

**Comment by py660** [comment]
BTW The email verification link is localhost/activate.php?...
It works under nic.webcr.top/app/activate.php?...

You might want to update this.

**Comment by santydesignscr** [comment]
Sorry, I updated that now, and launched a landing page

**Comment by santydesignscr** [comment]
Hello everyone,

I've just launched a new option for free subdomains at [NIC.WEBCR.TOP](https://nic.webcr.top). It's a straightforward process compared to the .wip.la registration method.

With NIC.WEBCR.TOP:
- **Register .webcr.top Subdomains:** Get your own .webcr.top subdomain quickly.
- **Edit Nameservers:** Easily manage your subdomains by adjusting nameservers.
- **Eliminate Subdomains:** Remove any unwanted subdomains effortlessly.

Now there won't be any issues with the pull request not being auto-merged. Additionally, this platform allows you to edit the nameservers of your subdomains and remove unused subdomains.

**Comment by santydesignscr** [comment]
If anyone have a domain and wants to give free subdomains on that plataform, send me a email to info@bytewave.webcr.top.

**Comment by santydesignscr** [comment]
### Want to Offer Free Subdomains?

Hello everyone,

If you have a domain and want to provide free subdomains to others, you can now send an email to [freedomains@bytewave.webcr.top](mailto:freedomains@bytewave.webcr.top) to have your domain added to the recently launched free subdomains provider, [NIC.WEBCR.TOP](https://nic.webcr.top). The platform has just been updated to support this feature.

**Comment by py660** [comment]
im worried about domain deprecation; idk how to port stuff over :(

**Comment by santydesignscr** [comment]
Ohh, this is bad, but I use my domain for my websites too, I will maintain it active, of another thing I can help you with you things, email me at info@bytewave.webcr.top

**Comment by santydesignscr** [comment]
Hello, why you closed my issue?

**Comment by santydesignscr** [comment]
@politician Do you want to colab to colab to make wip.la and cluster.ws to nic.webcr.top?
