### ISSUE TITLE
Domain is about to expire

### ISSUE THREAD

**Issue by py660** [Olivr/free-domain#1938]
@politician, I would like to know, are you officially deprecating cluster.ws and wip.la? whois says that this service will expire in a few months (september).

**Comment by ant-7802** [comment]
[STICKING OUT UR GYATT FOR THE RIZZLER UR SO SKIBIDI UR SO FANUM TAX](https://github.com/Olivr/free-domain/commit/d5ded43d6db38ff14a8c6ff754804c09b4ca9f4d)

**Comment by santydesignscr** [comment]
I don't think they will renew it

**Comment by politician** [comment]
There is a pending issue where we've hit the maximum records for CloudFlare. If I can find a solution, both domains shall be renewed.
