### ISSUE TITLE
delete domains

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [Olivr/free-domain#228]
I no longer need my domains:
william.cluster.ws
william.wip.la

How can I delete them? I've opened PR's: #226 and #227

**Comment by WilliamDavidHarrison** [comment]
@politician could you delete them?

**Comment by WilliamDavidHarrison** [comment]
@rmetzler @politician @akeuk @fu-sen

**Comment by fu-sen** [comment]
Don't ping unrelated people!

Also there is another issue about this: https://github.com/Olivr/free-domain/issues/185

**Comment by WilliamDavidHarrison** [comment]
> 

Can't they delete the domain though?

**Comment by ArtieFuzzz** [comment]
No, we can't delete domains nor can we merge pull requests.

**Comment by WilliamDavidHarrison** [comment]
> No, we can't delete domains nor can we merge pull requests.

Who is the owner of the domain? @ArtieFuzzz

**Comment by ArtieFuzzz** [comment]
politician Owns the domain and he's the only person who can merge pull requests that delete or modify domains

**Comment by WilliamDavidHarrison** [comment]
> politician Owns the domain and he's the only person who can merge pull requests that delete or modify domains

Do you think you cam ask him to delete it?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison please allow me one more week to look into this, I'm currently moving house/country and I don't want to merge PR's from my phone.
> 
> Thanks and sorry for the delay.

Ok. I understand I'm also moving house as well!

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison please allow me one more week to look into this, I'm currently moving house/country and I don't want to merge PR's from my phone.
> 
> Thanks and sorry for the delay.

@politician

**Comment by WilliamDavidHarrison** [comment]
@politician Do you think you can merge it now?

**Comment by WilliamDavidHarrison** [comment]
@politician Please merge it

**Comment by politician** [comment]
@WilliamDavidHarrison There is currently an error with the Terraform runs. I need to fix this first, then I'll merge your PRs.

**Comment by politician** [comment]
@WilliamDavidHarrison I have merged your PRs

**Comment by WilliamDavidHarrison** [comment]
Thanks
