### ISSUE TITLE
How to register subdomain at freedns.afraid.org?

### ISSUE THREAD

**Issue by maleeqB** [Olivr/free-domain#366]
Please how can I register my subdomain at FreeDNS?

I've searched through their [Registry](http://freedns.afraid.org/domain/registry) but I can't find cluster.ws domain

From the zones file, I realized someone was able to register zero.cluster.ws, and when I visit the [webpage](http://zero.cluster.ws), it says :

To create a free subdomain from any shared domain, you can visit the shared domain list.

Whereas the shared domain list is the same as Registry list above

**Comment by ArtieFuzzz** [comment]
Have you read the README?

**Comment by maleeqB** [comment]
Thanks a lot for your reply

Yes, I did check the README.

Under the **Where to go (after sign-up)** column for FreeDNS, [it links to where to add a domain name](https://freedns.afraid.org/domain/add.php), rather than a subdomain

And whenever I manually go to the subdomain section, there's no **cluster.ws** in the [registry](https://freedns.afraid.org/domain/registry)

**Comment by maleeqB** [comment]
Ok thanks, I've created a domain on FreeDNS

Initially it's shown as broken, after I've made the pull request here, it's no longer showing broken

But it's not mapping to my IP address. I've added my IP address on A record on FreeDNS, and there's a webserver running on my server

my domain is: **aaa.cluster.ws**

**Comment by maleeqB** [comment]
![This is a screenshot of it ](https://user-images.githubusercontent.com/64940608/204536721-853e8928-f346-4034-a0d9-a771e7184c70.jpg)

I can access **www.aaa.cluster.ws** but not **aaa.cluster.ws** itself. As you can see from the screenshot, both are meant to map to the same IP address


Please can you help me? What have I done wrong?

**Comment by ArtieFuzzz** [comment]
Are there meant to be Blank pages on both homepages of the website?

**Comment by maleeqB** [comment]
Thanks for your reply, actually I was trying to get websocket to work on Port 80, that's the reason why


You can check again now, I've turned on nginx

**Comment by maleeqB** [comment]
Ok seems both are working now, Both are mapping to the same IP address now

Wow

Thanks a lot for your help, I'm grateful

**Comment by ArtieFuzzz** [comment]
Glad to help!
