### ISSUE TITLE
Cloudflare Support ?

### ISSUE THREAD

**Issue by gaminglnk** [Olivr/free-domain#504]
Hey there
If these domains are compatible with Cloudflare, that would be fantastic.

Sub-domains are also supported by Cloudflare.
After a subdomain has an A or CName record added using another DNS service provider, Cloudflare usually recognises it as a domain.
I added an A record to a subdomain, then I was able to connect it with Cloudflare.

**Comment by ArtieFuzzz** [comment]
You can't register sub-domains on CloudFlare but you can create sub-domains via A, CNAME, etc Records.

Also you if you haven't read the README properly, it states:

> "Unfortunately, you cannot use Cloudflare with these domains because they are in fact subdomains and Cloudflare does not support adding a subdomain as a domain."

**Comment by IncognitoTGT** [comment]
#1179
