### ISSUE TITLE
No way to add to wip.la.yaml without the editor adding a newline to the last line

### ISSUE THREAD

**Issue by pepa65** [Olivr/free-domain#654]
I can't add a line to `wip.la.yaml` because the last line in the file doesn't have a newline. The github editor automatically adds that newline, and my Pull request fails...

**Comment by py660** [comment]
Try using github.dev #671

**Comment by pepa65** [comment]
It's a whole new way of working, but I got it to go..! Thank you for pointing out github.dev.
