### ISSUE TITLE
Make sure that only one line was affected

### ISSUE THREAD

**Issue by wimdaw** [Olivr/free-domain#723]
Failed to add domain name all the time ：Make sure that only one line was affected
How to solve it?
![QQ截图20230326005154](https://user-images.githubusercontent.com/29478061/227731265-e2517d16-7c1f-4aea-91e5-999e004f112c.png)

**Comment by NotMizzel** [comment]
I've reached out to @politician through email and he hasn't responded yet.

**Comment by wimdaw** [comment]
> 我已经联系到@politician通过电子邮件，他还没有回复。

But there are still people who can add successfully. Is it a problem with adding methods?

**Comment by wimdaw** [comment]
> I've reached out to @politician through email and he hasn't responded yet.

**Comment by NotMizzel** [comment]
The reason that it doesn't work is because you add the domain at the start of the file after the comments. Do this in github.dev or it will add a newline.
