### ISSUE TITLE
Change the dns

### ISSUE THREAD

**Issue by TryV** [Olivr/free-domain#859]
Hello.
I can't change my registred domain DNS.
Can you please help me do it?

`hendevane.cluster.ws: [ns101.cloudns.net, ns103.cloudns.net, ns102.cloudns.net, ns104.cloudns.net]`

**Comment by santydesignscr** [comment]
Hello everyone,

I've just launched a new option for free subdomains at [NIC.WEBCR.TOP](https://nic.webcr.top). It's a straightforward process compared to the .wip.la registration method.

With NIC.WEBCR.TOP:
- **Register .webcr.top Subdomains:** Get your own .webcr.top subdomain quickly.
- **Edit Nameservers:** Easily manage your subdomains by adjusting nameservers.
- **Eliminate Subdomains:** Remove any unwanted subdomains effortlessly.

Now there won't be any issues with the pull request not being auto-merged. Additionally, this platform allows you to edit the nameservers of your subdomains and remove unused subdomains.

**Comment by politician** [comment]
Sorry due to #30 currently not possible
